schema/mcp-agent.config.schema.json, src/mcp_agent/config.py, src/mcp_agent/llm/model_factory.py, src/mcp_agent/llm/providers/augmented_llm_generic.py, src/mcp_agent/llm/providers/augmented_llm_openai.py, tests/e2e/smoke/test_e2e_smoke.py
Adds support for Generic OpenAI endpoints, with locally running ollama for defaults. This allows the use of Ollama models by specifying a model name such as `generic.llama3.2:latest`. This feature should be considered advanced/experimental.
=> Support for Generic OpenAI LLMs (with ollama defaults)

pyproject.toml, src/mcp_agent/llm/providers/augmented_llm_generic.py, tests/unit/mcp_agent/llm/test_model_factory.py, uv.lock
Fix base_url handling for generic llm (hidden by tests having configuration)
=> fix baseurl/deepseek config error + unit test for same

src/mcp_agent/agents/workflow/router_agent.py, tests/integration/workflow/mixed/test_mixed_workflow.py
With the RouterResult 'result' in router_agent.py configured as 'Agent', the pydantic validation was failing whenever a Router agent selected a Parallel Agent type (or any other agent type besides 'Agent'). Since all the other agents seem to inherit BaseAgent, not Agent, I think this fix makes sense.
=> Changed RouterResult 'result' parameter from 'Agent' to 'BaseAgent'.

src/mcp_agent/llm/providers/augmented_llm_generic.py, src/mcp_agent/llm/providers/augmented_llm_openrouter.py
Aligns code with the docs: https://fast-agent.ai/models/llm_providers/#generic-openai-ollama
where GENERIC_BASE_URL and OPENROUTER_BASE_URL can be used to inject base urls
=> Fix base url reads from ENV for Generic and OpenRouter

schema/mcp-agent.config.schema.json, src/mcp_agent/config.py, src/mcp_agent/mcp/mcp_connection_manager.py, src/mcp_agent/mcp_server_registry.py
Today fast agent is using default timeout for sse_client which happens to be 5 minutes. for production systems this is too low as our observation is that with 5mins of inactivity with an mcp server it becomes unusable.
=> enhancement: allow sse_read_timeout to be configurable

README.md
This PR fixes syntax errors in the Python code examples within `README.md`:
- Added missing commas in decorators.
- Fixed incorrect list syntax.
- Corrected misplaced parentheses in the agent definition.
Now the snippets can be directly copied without syntax issues.
=> Fix syntax errors in sample code

src/mcp_agent/llm/augmented_llm.py
This enhancement performs a recursive merge of ``request_params`` set initially on the agent with parameters passed in during an execution step. Consider the example below that adds a session identifier at runtime to a specific step in the process:
```python
@app.agent(
name="Generator",
request_params=RequestParams(
maxTokens=DEFAULT_MAX_TOKENS,
use_history=False,
metadata={
"metadata": {
"trace_name": "Novelist",
"tags": TAGS,
},
},
)
async def main() -> None:
async with app.run() as agent:
session_id = str(uuid4()).replace("-", "")
result = agent.Optimizer.structured(
prompt,
SomePydanticObject,
request_params=RequestParams(
metadata={"metadata": {"session_id": session_id}}
)
```
Prior to this update, the inner ``metadata`` would be set to ``{"session_id": session_id}`` and basically …
=> LiteLLM+LangFuse Support: Enhancing how request_params are overridden

src/mcp_agent/config.py, src/mcp_agent/mcp/mcp_connection_manager.py, src/mcp_agent/mcp_server_registry.py
Allows MCP server yaml files to specify a `cwd` setting, which is just passed through to the `StdioServerParameters` class.
My specific use case was launching tool servers that exist elsewhere on disk, e.g.,:
1. fast-agent app is in /home/work/app
2. MCP tool server I'm developing is in /home/work/toolbox1
3. Configure fastagent.config.yaml to use my `toolbox1` tools, running from `/home/work/toolbox1`
4. Run fast-agent app
5. Make some edits to toolbox1
6. Goto 4...
Example usage:
fastagent.config.yaml:
```yaml
mcp:
servers:
toolbox1:
command: "node"
args: ["dist/index.js"]
cwd: "/home/work/toolbox1"
```
=> Added MCP server `cwd` setting

src/mcp_agent/agents/workflow/orchestrator_agent.py
Fixing a small bug in OrchestratorAgent that was referencing the wrong ``PlanResult`` property when checking ``max_iterations``.
=> Renaming max_steps_reached to max_iterations_reached on PlanResult

.gitignore, .vscode/fastagent.config.schema.json, src/mcp_agent/cli/commands/README.md, src/mcp_agent/cli/commands/go.py, src/mcp_agent/cli/commands/url_parser.py, src/mcp_agent/config.py, src/mcp_agent/core/fastagent.py, src/mcp_agent/core/request_params.py, src/mcp_agent/mcp/mcp_connection_manager.py, src/mcp_agent/mcp/prompts/prompt_server.py, src/mcp_agent/mcp_server/agent_server.py, src/mcp_agent/mcp_server_registry.py, src/mcp_agent/resources/examples/mcp/state-transfer/fastagent.config.yaml, tests/integration/api/fastagent.config.yaml, tests/integration/api/test_cli_and_mcp_server.py, tests/integration/prompt-server/fastagent.config.yaml, tests/integration/prompt-server/test_prompt_server_integration.py, tests/unit/mcp_agent/cli/commands/test_url_parser.py
- Prompt Server supports Streaming HTTP
- Run Agents/Workflows as Streaming HTTP MCP Servers
- Connect to Streaming HTTP MCP Servers
- Add --url=<url> and --auth=<token> to `fast-agent go` supporting direct connection to multiple SSE/Streaming HTTP Servers
=> Add Streaming HTTP Support for Client, Server and prompt-server.

src/mcp_agent/mcp/mcp_aggregator.py
This PR fixed the issue #226, please refer to the description in the issue for more details.
=> fix(#226): Error in tool list changed callback

src/mcp_agent/llm/providers/augmented_llm_google_native.py
When `use_history=False`, the last message should be used instead of an empty list.
=> Fix the issue of google native when `use_history=False`

src/mcp_agent/core/direct_factory.py, tests/integration/workflow/parallel/test_parallel_agent.py
The `include_request` parameter from the `@fast.parallel` decorator was not being passed to the `ParallelAgent` constructor, causing it to always default to `True` regardless of the decorator setting.
- Fix: Add missing `include_request` parameter in `direct_factory.py`
- Test: Add tests to verify `include_request` behavior
Fixes issue where setting `include_request=False` had no effect.
Files Changed:
`src/mcp_agent/core/direct_factory.py`
`tests/integration/workflow/parallel/test_parallel_agent.py`
=> Fix: Pass include_request parameter to ParallelAgent constructor

src/mcp_agent/core/agent_types.py, src/mcp_agent/core/direct_decorators.py, src/mcp_agent/core/direct_factory.py, src/mcp_agent/llm/augmented_llm.py, src/mcp_agent/mcp/mcp_agent_client_session.py, src/mcp_agent/mcp/mcp_aggregator.py, src/mcp_agent/mcp/sampling.py, tests/integration/api/test_provider_keys.py
This argument allows us to create agents with different API KEYs at runtime. It helps implement workflows that require users to provide an API KEY.
=> Add `api_key` argument to specify API KEY when creating agents

examples/mcp/mcp-filtering/fastagent.config.yaml, examples/mcp/mcp-filtering/fastagent.secrets.yaml.example, examples/mcp/mcp-filtering/mcp_server.py, examples/mcp/mcp-filtering/test_mcp_filtering.py, src/mcp_agent/agents/base_agent.py, src/mcp_agent/core/agent_types.py, src/mcp_agent/core/direct_decorators.py, src/mcp_agent/core/enhanced_prompt.py, tests/e2e/mcp_filtering/fastagent.config.yaml, tests/e2e/mcp_filtering/filtering_test_server.py, tests/e2e/mcp_filtering/test_mcp_filtering.py
Here is an implementation of agent-level MCP filtering.  This allows filtering of the tools, resources and prompts from the MCP server in the agent decorator configuration.  
This is fully backwards compatible - if no filters are applied, then all tools/resources/prompts are returned.
Includes example and e2e test
refs #280 
if this is something that is considered for inclusion, I can update the docs repo next
=> Mcp filtering

examples/bedrock/fast-agent.config.yaml, pyproject.toml, src/mcp_agent/config.py, src/mcp_agent/core/interactive_prompt.py, src/mcp_agent/llm/model_factory.py, src/mcp_agent/llm/provider_types.py, src/mcp_agent/llm/providers/augmented_llm_bedrock.py, src/mcp_agent/logging/logger.py, uv.lock
This is a proper AWS Bedrock provider for full support of all AWS Bedrock models
features:
- streaming responses for all providers
- tool use for all providers
- streaming responses during tool use for models that support it; non-streaming response during tool use otherwise
- uses the AWS SDK directly, eliminating the need for proxy gateways such as Bedrock Access Gateway, LiteLLM, TensorZero, etc.
- Tool information is supplied to the various models in the proper format for that model
I tried using Bedrock with fast-agent via:
**Bedrock Access Gateway** - chat worked, but tool support was broken
**LiteLLM proxy**: chat worked, but tool support also broken
**TensorZero gateway**: chat worked, but tool support also broken.  Additionally, there was a lot of complexity setting up the TOML …
=> Aws Bedrock provider native support

src/mcp_agent/logging/transport.py
It is inspired by [this PR](https://github.com/lastmile-ai/mcp-agent/pull/159), to fix the issue mentioned in #284 .
=> Adjust the lifetime of event queue for listeners in `AsyncEventBus`

src/mcp_agent/llm/providers/augmented_llm_bedrock.py
On August 5th, AWS announced support for OpenAI's recently released OSS 20b and 120b models.  This adds support for them in the Bedrock augmented LLM provider
internal ref: DEV-1844
=> Add support for AWS Bedrock OpenAI OSS models

src/mcp_agent/core/enhanced_prompt.py
- Surfaces EXIT option directly in toolbar without requiring '/' prefix or remembering how to exit
=> Fix - Improve exit command visibility in interactive prompt

src/mcp_agent/event_progress.py, src/mcp_agent/mcp/mcp_agent_client_session.py, src/mcp_agent/mcp/mcp_aggregator.py, src/mcp_agent/mcp/mcp_connection_manager.py
This change adds a few features:
- supresses mcp sse_reader messages.  Currently, when an SSE MCP server goes offline, pages of stack trace flood the console output.  This is coming from the mcp library.  Added a filter to suppress these errors
- added SSE reconnect logic.  Currently, if an SSE server is down and the agent attempts a tool call, an error is displayed saying that the tool call failed.  Even if the SSE server comes back online, the agent will not be able to call a tool successfully without rebooting the agent.  This changes fixes that, and now a reconnection attempt is made, followed by a successful tool call
This is presented as an alternative to pull request 291 (Dynamic MCP handling)
If accepted, I will do a similar pull request for the HTTP transport
=> Add MCP SSE server reconnection

src/mcp_agent/core/fastagent.py
As a developer, I should be able to pass low-level configurations to the underlying `MCPApp` while creating my `FastAgent` object.
For eg: `MCPApp` allows custom implementation for `human_input_callback` which the agents within `FastAgent` can use when set with `human_input=True`. This is useful for when we have custom logic to accept user input other than just STDIN.
Similarly, any other configurations that can be set during application creation can be passed via the `kwargs`
=> Support kwargs for MCPApp

examples/mcp/elicitations/elicitation_forms_server.py, src/mcp_agent/human_input/elicitation_form.py
**Key Changes:**
- Select input height based on actual newlines present in default content
- Improve keybindings: Ctrl+J insert new lines, Enter submits
- Adjust input field height dynamicly based on newlines in input
**Demo:** https://asciinema.org/a/lCQtSe9tmN2gQucJcb96p1vbB
=> Improve elicitation input handling for multiline content

src/fast_agent/core/agent_app.py
Hi,
I wanted to try-out the commit method you described in [this comment](https://github.com/evalstate/fast-agent/issues/393#issuecomment-3299314847).
This is a trivial check and intent of this PR is much more to familiarize myself with the workflow rather than anything else (but also could mean a fast merge?)
Regards,
Chris
PS: while trivial it actually makes sense to add this because it solves potential bug on line 115 of the same file: `return next(iter(self._agents.values()))` (raises `StopIteration`)
=> chore: make a check for the length of the agent dict

src/fast_agent/agents/agent_types.py, src/fast_agent/core/agent_app.py, src/fast_agent/core/direct_factory.py, tests/e2e/workflow/test_orchestrator_puzzle.py
First thing I noticed, looking for the things I could improve upon was this one giant block of repeating code. So I removed it, making sure the order of operations is still the same. 
Also did a small change to the type -> used `StrEnum` + `auto()` just because it results in code that is harder to do typos in (one place for a typo not two).
=> Remove the boilerplate in the `create_agents_in_dependency_order` function

README.md
Update README to leverage the correct --url parameter for launch fast-agent from cli with MCP server
Based on the current README example it is stated that the fast-agent server should be started with the following command to connect to an MCP server
```
fast-agent go https://hf.co/mcp
```
This throws an error
```
No such command 'https://hf.co/mcp'.
```
Therefore this appears to no longer be the case based on my testing and the file which contains the arguments for the `go` function here: https://github.com/evalstate/fast-agent/blob/6ee0b2f1adf2f00ee89b950d9225c7c88e006ec9/src/fast_agent/cli/commands/go.py#L293
I have therefore updated the readme to reflect the correct usage as 
```
fast-agent go --url https://hf.co/mcp
```
=> README Update - Incorrect Example
